/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package outras;

import cadastros.Cad_Turma;
import cadastros.Cad_Cursos;
import cadastros.Cad_Aluno;
import cadastros.Cad_Disciplina;
import cadastros.Cad_Professor;
import consultas.Cons_Aluno;
import consultas.Cons_Cursos;
import consultas.Cons_Disciplina;
import consultas.Cons_Professor;
import consultas.Cons_Turma;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ancelmocastro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        //executar a tela maximizada...
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(244, 246, 246));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCursos = new javax.swing.JButton();
        jbMatricula = new javax.swing.JButton();
        jbMatricula1 = new javax.swing.JButton();
        jbMatricula2 = new javax.swing.JButton();
        jbMatricula3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuProfessor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCadastrarAluno = new javax.swing.JMenuItem();
        jMenuItem_Turma = new javax.swing.JMenuItem();
        jMenuItem_Professor = new javax.swing.JMenuItem();
        jMenuItem_Disciplinas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Cons_Cursos = new javax.swing.JMenuItem();
        jMenuItem_Consultar_Alunos = new javax.swing.JMenuItem();
        jMenuItem_Consultar_Professores = new javax.swing.JMenuItem();
        jMenuItem_Consulta_Turma = new javax.swing.JMenuItem();
        jMenuItem_Consultar_Disciplina = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Modular  Escolar");
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(115, 207, 112));

        jbCursos.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jbCursos.setForeground(new java.awt.Color(0, 153, 102));
        jbCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Certificate-icon.png"))); // NOI18N
        jbCursos.setText("Cadastrar Cursos");
        jbCursos.setToolTipText("Realiza cadastros de Cursos");
        jbCursos.setContentAreaFilled(false);
        jbCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCursos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCursos.setOpaque(true);
        jbCursos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCursosActionPerformed(evt);
            }
        });

        jbMatricula.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jbMatricula.setForeground(new java.awt.Color(0, 153, 102));
        jbMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Teacher-male-icon.png"))); // NOI18N
        jbMatricula.setText("Gerenciar Alunos");
        jbMatricula.setToolTipText("Realiza matrículas de Alunos cadastrados");
        jbMatricula.setContentAreaFilled(false);
        jbMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMatricula.setOpaque(true);
        jbMatricula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMatriculaActionPerformed(evt);
            }
        });

        jbMatricula1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jbMatricula1.setForeground(new java.awt.Color(0, 153, 102));
        jbMatricula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Science-Classroom-icon.png"))); // NOI18N
        jbMatricula1.setText("Turmas");
        jbMatricula1.setToolTipText("Realiza matrículas de Alunos cadastrados");
        jbMatricula1.setContentAreaFilled(false);
        jbMatricula1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMatricula1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMatricula1.setOpaque(true);
        jbMatricula1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMatricula1ActionPerformed(evt);
            }
        });

        jbMatricula2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jbMatricula2.setForeground(new java.awt.Color(0, 153, 102));
        jbMatricula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Books-icon.png"))); // NOI18N
        jbMatricula2.setText("Disciplinas");
        jbMatricula2.setToolTipText("Realiza matrículas de Alunos cadastrados");
        jbMatricula2.setContentAreaFilled(false);
        jbMatricula2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMatricula2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMatricula2.setOpaque(true);
        jbMatricula2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMatricula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMatricula2ActionPerformed(evt);
            }
        });

        jbMatricula3.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jbMatricula3.setForeground(new java.awt.Color(0, 153, 102));
        jbMatricula3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/professor-icone.png"))); // NOI18N
        jbMatricula3.setText("Professor");
        jbMatricula3.setToolTipText("Realiza matrículas de Alunos cadastrados");
        jbMatricula3.setContentAreaFilled(false);
        jbMatricula3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMatricula3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMatricula3.setOpaque(true);
        jbMatricula3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbMatricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMatricula3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbMatricula2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMatricula1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jbMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMatricula3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/a4a4781ea9a21bad74cb8a535c471ce22652424b.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SME - SISTEMA MODULAR ESCOLAR");

        jMenu1.setText("Sistema");

        jMenuProfessor.setText("Transações");
        jMenuProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfessorActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cadastrar Cursos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuItem1);

        jMenuItemCadastrarAluno.setText("Cadastrar Aluno");
        jMenuItemCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuItemCadastrarAluno);

        jMenuItem_Turma.setText("Cadastrar Turmas");
        jMenuItem_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TurmaActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuItem_Turma);

        jMenuItem_Professor.setText("Cadastrar Professores");
        jMenuItem_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ProfessorActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuItem_Professor);

        jMenuItem_Disciplinas.setText("Cadastrar Disciplinas");
        jMenuItem_Disciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DisciplinasActionPerformed(evt);
            }
        });
        jMenuProfessor.add(jMenuItem_Disciplinas);
        jMenuProfessor.add(jSeparator1);

        jMenuItem6.setText("Matricular Aluno");
        jMenuProfessor.add(jMenuItem6);

        jMenu1.add(jMenuProfessor);
        jMenu1.add(jSeparator2);

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem_Cons_Cursos.setText("Cursos");
        jMenuItem_Cons_Cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Cons_CursosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Cons_Cursos);

        jMenuItem_Consultar_Alunos.setText("Aluno");
        jMenuItem_Consultar_Alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultar_AlunosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Consultar_Alunos);

        jMenuItem_Consultar_Professores.setText("Professores");
        jMenuItem_Consultar_Professores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultar_ProfessoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Consultar_Professores);

        jMenuItem_Consulta_Turma.setText("Turmas");
        jMenuItem_Consulta_Turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consulta_TurmaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Consulta_Turma);

        jMenuItem_Consultar_Disciplina.setText("Disciplinas");
        jMenuItem_Consultar_Disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Consultar_DisciplinaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Consultar_Disciplina);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");

        jMenuItem11.setText("Sobre...");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Para abrir telas
     *
     * @param tela
     */
    public void abrirTela(javax.swing.JDialog tela) {
        tela.setVisible(true);
    }


    private void jbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCursosActionPerformed
        // TODO add your handling code here:
        new Cons_Cursos(null, true).setVisible(true);
    }//GEN-LAST:event_jbCursosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jbCursos.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMatriculaActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Aluno(this, rootPaneCheckingEnabled));
    }//GEN-LAST:event_jbMatriculaActionPerformed

    private void jbMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMatricula1ActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Turma(this, rootPaneCheckingEnabled));
    }//GEN-LAST:event_jbMatricula1ActionPerformed

    private void jbMatricula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMatricula2ActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Disciplina(this, rootPaneCheckingEnabled));
    }//GEN-LAST:event_jbMatricula2ActionPerformed

    private void jbMatricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMatricula3ActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Professor(this, rootPaneCheckingEnabled));
    }//GEN-LAST:event_jbMatricula3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Sobre(null, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItemCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cad_Aluno(null, rootPaneCheckingEnabled, "incluir"));
    }//GEN-LAST:event_jMenuItemCadastrarAlunoActionPerformed

    private void jMenuItem_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TurmaActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cad_Turma(null, true, 0));
    }//GEN-LAST:event_jMenuItem_TurmaActionPerformed

    private void jMenuProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfessorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuProfessorActionPerformed

    private void jMenuItem_DisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DisciplinasActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cad_Disciplina(this, true, null));
    }//GEN-LAST:event_jMenuItem_DisciplinasActionPerformed

    private void jMenuItem_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ProfessorActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cad_Professor(null, true));
    }//GEN-LAST:event_jMenuItem_ProfessorActionPerformed

    private void jMenuItem_Consulta_TurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consulta_TurmaActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Turma(this, true));
    }//GEN-LAST:event_jMenuItem_Consulta_TurmaActionPerformed

    private void jMenuItem_Cons_CursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Cons_CursosActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Cursos(this, true));
    }//GEN-LAST:event_jMenuItem_Cons_CursosActionPerformed

    private void jMenuItem_Consultar_AlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultar_AlunosActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Aluno(this, true));
    }//GEN-LAST:event_jMenuItem_Consultar_AlunosActionPerformed

    private void jMenuItem_Consultar_ProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultar_ProfessoresActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Professor(this, true));
    }//GEN-LAST:event_jMenuItem_Consultar_ProfessoresActionPerformed

    private void jMenuItem_Consultar_DisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Consultar_DisciplinaActionPerformed
        // TODO add your handling code here:
        abrirTela(new Cons_Disciplina(this, true));
    }//GEN-LAST:event_jMenuItem_Consultar_DisciplinaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Anteção!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        jMenuItem7.doClick();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemCadastrarAluno;
    private javax.swing.JMenuItem jMenuItem_Cons_Cursos;
    private javax.swing.JMenuItem jMenuItem_Consulta_Turma;
    private javax.swing.JMenuItem jMenuItem_Consultar_Alunos;
    private javax.swing.JMenuItem jMenuItem_Consultar_Disciplina;
    private javax.swing.JMenuItem jMenuItem_Consultar_Professores;
    private javax.swing.JMenuItem jMenuItem_Disciplinas;
    private javax.swing.JMenuItem jMenuItem_Professor;
    private javax.swing.JMenuItem jMenuItem_Turma;
    private javax.swing.JMenu jMenuProfessor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbCursos;
    private javax.swing.JButton jbMatricula;
    private javax.swing.JButton jbMatricula1;
    private javax.swing.JButton jbMatricula2;
    private javax.swing.JButton jbMatricula3;
    // End of variables declaration//GEN-END:variables
}
