/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentoescolar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ancelmocastro
 */
public class TelaCadCursos extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadCursos
     */
    public TelaCadCursos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //impede o redimensionamento da tela...
        setResizable(false);
        
        //posiciona no centro da tela do PC...
        setLocationRelativeTo(null);
        
        //método mostrardados()...
        mostrardados("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCodigo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cursos");
        setPreferredSize(null);

        jpCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados:"));

        jLabel3.setText("Nome do Curso:");

        jlCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 25)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(255, 0, 51));
        jlCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpCodigoLayout = new javax.swing.GroupLayout(jpCodigo);
        jpCodigo.setLayout(jpCodigoLayout);
        jpCodigoLayout.setHorizontalGroup(
            jpCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCodigoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpCodigoLayout.createSequentialGroup()
                        .addGroup(jpCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpCodigoLayout.setVerticalGroup(
            jpCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados:"));

        jtTabela.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome do Curso"
            }
        ));
        jtTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbSalvar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/floppy-icon.png")); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setToolTipText("Cadastrar Curso");
        jbSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbRemover.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbRemover.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/Delete-file-icon.png")); // NOI18N
        jbRemover.setText("Remover");
        jbRemover.setToolTipText("Remover o Curso selecionado");
        jbRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/Search-icon.png")); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setToolTipText("Fazer uma Busca");
        jbBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/Apps-Dialog-Shutdown-icon.png")); // NOI18N
        jbSair.setText("Sair");
        jbSair.setToolTipText("Sair do Cadastro de Cursos");
        jbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/edit-validated-icon.png")); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setToolTipText("Editar e Alterar um Curso");
        jbAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon("/Users/ancelmocastro/Documents/NetBeansProjects/Java/AppEscola/Imagens/New-file-icon.png")); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setToolTipText("Inserir um novo Curso");
        jbNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbRemover)
                    .addComponent(jbAlterar)
                    .addComponent(jbBuscar)
                    .addComponent(jbSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void mostrardados(String valor){
        
      Conectar cc = new Conectar();
      Connection cn = cc.Escola();
      
      DefaultTableModel modelo = new DefaultTableModel(){
          
        //método que impede o mode de edição na Tabela....
        @Override
        public boolean isCellEditable(int linhas, int colunas) {
          if (colunas == 2)
            return true;
          else
            return false;
       }
   };
    
    modelo.addColumn("Código");
    modelo.addColumn("Nome do Curso");
          
    jtTabela.setModel(modelo);
      
    String sql = "";
      
    if (valor.equals(""))
      sql = "SELECT * FROM Cursos";
    else
      sql = "SELECT * FROM Cursos WHERE (codcurso='"+valor+"' OR nomecurso='"+valor+"')";
        
    String[]dados = new String [2];
        
    try
      {
        Statement st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next())
          {
            dados[0] = rs.getString(1);
            dados[1] = rs.getString(2);

            modelo.addRow(dados);
          }
        jtTabela.setModel(modelo);
      }
    catch(SQLException ex)
      {
        Logger.getLogger(dados.class.getName()).log(Level.SEVERE,null,ex);
      }  
    
    jbNovo.setEnabled(false);
    jbRemover.setEnabled(false);
    jbAlterar.setEnabled(false);
    jbBuscar.setEnabled(false);
  }
    
    
    private void jtTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaMouseClicked
      // TODO add your handling code here:
        
    }//GEN-LAST:event_jtTabelaMouseClicked

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
      // TODO add your handling code here:
      Conectar c = new Conectar();
      Connection cn = c.Escola();

      try
        {

          if (jtNome.getText().isEmpty() == false)
            {
               PreparedStatement pst = cn.prepareStatement("INSERT INTO Cursos (nomecurso) VALUES(?)");

               pst.setString(1,jtNome.getText());

               int a = pst.executeUpdate();

               if (a > 0)
                 {
                    JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!","Informação",JOptionPane.INFORMATION_MESSAGE);
                    mostrardados("");
                    jtNome.setText("");
                    jtNome.grabFocus();
                 }
               else
                 {
                    JOptionPane.showMessageDialog(null,"Error ao cadastrar!","Erro",JOptionPane.ERROR_MESSAGE);
                    jtNome.grabFocus();
                 }
           }
          else
            {
               JOptionPane.showMessageDialog(null,"Informe o nome do Curso!","Aviso",JOptionPane.WARNING_MESSAGE);
               jtNome.grabFocus();
            }
        }
      catch(Exception e)
        {

        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
      // TODO add your handling code here:
        
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
      // TODO add your handling code here:  
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
      // TODO add your handling code here:
        
    }//GEN-LAST:event_jbNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadCursos dialog = new TelaCadCursos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JPanel jpCodigo;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
}
